logging:
  level:
    org.springframework: WARN
    org.flywaydb: WARN

spring:
  datasource:
    url: jdbc:h2:mem:metering-demo
  jpa:
    open-in-view: false
    show-sql: false

server:
  port: 9090
